### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Lanfr** [751496032/ZRouter#10]
1 ERROR: ArkTS:ERROR File: D:/homaryos_progect/ZRouter/RouterApi/src/main/ets/api/RouterMgr.ets:210:10
 Object literal must correspond to some explicitly declared class or interface (arkts-no-untyped-obj-literals)

2 ERROR: ArkTS:ERROR File: D:/homaryos_progect/ZRouter/RouterApi/src/main/ets/api/RouterMgr.ets:415:9
 Object literal must correspond to some explicitly declared class or interface (arkts-no-untyped-obj-literals)

3 ERROR: ArkTS:ERROR File: D:/homaryos_progect/ZRouter/RouterApi/src/main/ets/model/NavOptions.ets:10:14
 Cannot find name 'LaunchMode'.

**Comment by 751496032** [comment]
IDE 版本是多少，清IDE缓存重启试试
