### ISSUE TITLE
ZRouter.getInstance().redirect 登录成功后 旧的跳转参数丢失

### ISSUE THREAD

**Issue by damilili** [751496032/ZRouter#14]
@hzw+zrouter@1.2.0/oh_modules/@hzw/zrouter/src/main/ets/model/NavDestBuilder.ets:131

```
//以下是NavDestBuilder 源码，注释处是怀疑点
public redirect(name: string) {
    this.updateCurrentStackName()
    if (this.optionsImpl.onPopListener) {
      //问题 ：第二个参数 应该传 this 还是 this.optionsImpl.params
      this.routerMgr.redirectForResult2<T>(name, this, this.optionsImpl.onPopListener,this)
    } else {
      this.routerMgr.redirect(name, this)
    }
  }
```

**Comment by 751496032** [comment]
> @hzw+zrouter@1.2.0/oh_modules/@hzw/zrouter/src/main/ets/model/NavDestBuilder.ets:131
> 
> ```
> //以下是NavDestBuilder 源码，注释处是怀疑点
> public redirect(name: string) {
>     this.updateCurrentStackName()
>     if (this.optionsImpl.onPopListener) {
>       //问题 ：第二个参数 应该传 this 还是 this.optionsImpl.params
>       this.routerMgr.redirectForResult2<T>(name, this, this.optionsImpl.onPopListener,this)
>     } else {
>       this.routerMgr.redirect(name, this)
>     }
>   }
> ```

谢谢指正，确实存在问题，可以临时使用ZRouter.redirectForResult2()方法来替代ZRouter.getInstance().redirect()。

**Comment by 751496032** [comment]
> @hzw+zrouter@1.2.0/oh_modules/@hzw/zrouter/src/main/ets/model/NavDestBuilder.ets:131
> 
> ```
> //以下是NavDestBuilder 源码，注释处是怀疑点
> public redirect(name: string) {
>     this.updateCurrentStackName()
>     if (this.optionsImpl.onPopListener) {
>       //问题 ：第二个参数 应该传 this 还是 this.optionsImpl.params
>       this.routerMgr.redirectForResult2<T>(name, this, this.optionsImpl.onPopListener,this)
>     } else {
>       this.routerMgr.redirect(name, this)
>     }
>   }
> ```

已修复 升级到1.3.0
