### ISSUE TITLE
@Route 不支持引用常量

### ISSUE THREAD

**Issue by Enid516** [751496032/ZRouter#2]
@Route({ name: 'MineSettingPage'}) 有效

@Route({ name: RouthPath.MineSettingPage}) 无效

export class RouthPath{
  static readonly MINE_SETTING_PAGE = 'MineSettingPage'
}

**Comment by 751496032** [comment]
> @route({ name: 'MineSettingPage'}) 有效
> 
> @route({ name: RouthPath.MineSettingPage}) 无效
> 
> export class RouthPath{ static readonly MINE_SETTING_PAGE = 'MineSettingPage' }

ts语法是不支持的，不能像java一样

**Comment by 07ami** [comment]
> > @route({ name: 'MineSettingPage'}) 有效
> > @route({ name: RouthPath.MineSettingPage}) 无效
> > export class RouthPath{ static readonly MINE_SETTING_PAGE = 'MineSettingPage' }
> 
> ts语法是不支持的，不能像java一样

但是正常的字面量是支持RouthPath.MineSettingPage这样引用的，只有@Route这个地方不支持

**Comment by 751496032** [comment]
> > > @route({ name: 'MineSettingPage'}) 有效
> > > @route({ name: RouthPath.MineSettingPage}) 无效
> > > export class RouthPath{ static readonly MINE_SETTING_PAGE = 'MineSettingPage' }
> > 
> > 
> > ts语法是不支持的，不能像java一样
> 
> 但是正常的字面量是支持RouthPath.MineSettingPage这样引用的，只有@route这个地方不行 所以我觉得这个问题是能解决的。 点击routte后看到param是一个interface，如果声明为class能提高对数据的处理能力。问题应该就出在对Param的数据解析或处理。 希望能解决这个问题，帮助确实会很大。

已支持，插件升级到1.0.7即可

**Comment by Enid516** [comment]
最新版本的插件没找到下载的地方呢？？





little&nbsp;kivi
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "751496032/ZRouter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月10日(星期四) 上午10:37
***@***.***&gt;;
抄送:&nbsp;"little ***@***.******@***.***&gt;;
主题:&nbsp;Re: [751496032/ZRouter] @Route 不支持引用常量 (Issue #2)





    
@route({ name: 'MineSettingPage'}) 有效
 @route({ name: RouthPath.MineSettingPage}) 无效
 export class RouthPath{ static readonly MINE_SETTING_PAGE = 'MineSettingPage' }
  
ts语法是不支持的，不能像java一样
  
***@***.***这个地方不行 所以我觉得这个问题是能解决的。 点击routte后看到param是一个interface，如果声明为class能提高对数据的处理能力。问题应该就出在对Param的数据解析或处理。 希望能解决这个问题，帮助确实会很大。
  
已支持，插件升级到1.0.7即可
