### ISSUE TITLE
Index.ets导出问题

### ISSUE THREAD

**Issue by hanlin19900610** [751496032/ZRouter#3]
Index.ets  文件下面的
import { Route } from './src/main/ets/annotation/Route'
import { ZRouter } from './src/main/ets/api/Router'
要改成
export { Route } from './src/main/ets/annotation/Route'
export { ZRouter } from './src/main/ets/api/Router'

**Comment by 751496032** [comment]
> Index.ets 文件下面的 import { Route } from './src/main/ets/annotation/Route' import { ZRouter } from './src/main/ets/api/Router' 要改成 export { Route } from './src/main/ets/annotation/Route' export { ZRouter } from './src/main/ets/api/Router'

谢谢指正

**Comment by hanlin19900610** [comment]
刚开始用你这个库, 自动导入的时候还没发现, 手动导入的时候发现了, 希望尽快改一下发个版, 谢谢

**Comment by 751496032** [comment]
> 刚开始用你这个库, 自动导入的时候还没发现, 手动导入的时候发现了, 希望尽快改一下发个版, 谢谢

已修复 1.0.2
