### ISSUE TITLE
路由注册的时候name不能传递变量

### ISSUE THREAD

**Issue by 07ami** [751496032/ZRouter#5]
我想给name字段一个变量Page.pageB，但是这样就跳转不成功了。如下示例代码：
class Page {
  static pageB = "PageB"
}

@Route({ name: Page.pageB })
@Component
export struct PageB {
...

这里给name字段赋值变量是一个切实的需求。如果注册的地方和引用的地方都直接用字符串，一方面，不小心可能会打错字母；另一方面，跳转引用的时候需要找到对于页面然后复制这个字符串，很繁琐。
而如果通过变量引用的方式，就可以避免上面的这两个问题。

**Comment by 751496032** [comment]
ts语法上不支持，后面计划用插件自动一个路由名称常量类

**Comment by 751496032** [comment]
> 我想给name字段一个变量Page.pageB，但是这样就跳转不成功了。如下示例代码： class Page { static pageB = "PageB" }
> 
> @route({ name: Page.pageB }) @component export struct PageB { ...
> 
> 这里给name字段赋值变量是一个切实的需求。如果注册的地方和引用的地方都直接用字符串，一方面，不小心可能会打错字母；另一方面，跳转引用的时候需要找到对于页面然后复制这个字符串，很繁琐。 而如果通过变量引用的方式，就可以避免上面的这两个问题。


ts语法上不支持，后面计划用插件自动一个路由名称常量类

**Comment by 751496032** [comment]
> 我想给name字段一个变量Page.pageB，但是这样就跳转不成功了。如下示例代码： class Page { static pageB = "PageB" }
> 
> @route({ name: Page.pageB }) @component export struct PageB { ...
> 
> 这里给name字段赋值变量是一个切实的需求。如果注册的地方和引用的地方都直接用字符串，一方面，不小心可能会打错字母；另一方面，跳转引用的时候需要找到对于页面然后复制这个字符串，很繁琐。 而如果通过变量引用的方式，就可以避免上面的这两个问题。

已支持 ，插件升级到1.0.7
