### ISSUE TITLE
 ZRouter.redirectForResult的回调没有被触发

### ISSUE THREAD

**Issue by 07ami** [751496032/ZRouter#6]
当我通过  ZRouter.redirectForResult 跳转到另一个页面，然后再另一个页面通过 ZRouter.popWithResult(true) 方法返回后。
ZRouter.redirectForResult 里的回调方法并没有被触发

`
调用的地方
  aboutToAppear(): void {
    ZRouter.addGlobalInterceptor(async (info) => {
      Log.i("GlobalInterceptor", JSON.stringify(info.data), info.notRegistered.toString(), info.needLogin.toString())
      if (info.notRegistered) {
        ZRouter.redirect("PageNotFound")
        return
      }
      //todo-don 这里需要验证是否比global早
      // let isLogin = Global.isLogin
      let isLogin = false
      if (info.needLogin && !isLogin) {
        let param = ZRouter.getParamByName(info.data?.name ?? 'tmp')
        ZRouter.redirectForResult("PageB", param, (data) => {
          Log.i("GlobalInterceptor--resultCallBack")
          if (data.result) {
            return true
          }
          return false
        })
      }
    })
  }

返回的页面（即PageB页面）
    NavDestination() {
      Column() {
        Text("路由跳转C").fontColor(Color.Red).onClick(() => {
          AppStorage.setOrCreate('isLogin', true)
          ZRouter.popWithResult(true)
        })
      }
    }
`

**Comment by 751496032** [comment]
ok 晚点看看

**Comment by 751496032** [comment]
> 当我通过 ZRouter.redirectForResult 跳转到另一个页面，然后再另一个页面通过 ZRouter.popWithResult(true) 方法返回后。 ZRouter.redirectForResult 里的回调方法并没有被触发
> 
> ` 调用的地方 aboutToAppear(): void { ZRouter.addGlobalInterceptor(async (info) => { Log.i("GlobalInterceptor", JSON.stringify(info.data), info.notRegistered.toString(), info.needLogin.toString()) if (info.notRegistered) { ZRouter.redirect("PageNotFound") return } //todo-don 这里需要验证是否比global早 // let isLogin = Global.isLogin let isLogin = false if (info.needLogin && !isLogin) { let param = ZRouter.getParamByName(info.data?.name ?? 'tmp') ZRouter.redirectForResult("PageB", param, (data) => { Log.i("GlobalInterceptor--resultCallBack") if (data.result) { return true } return false }) } }) }
> 
> 返回的页面（即PageB页面） NavDestination() { Column() { Text("路由跳转C").fontColor(Color.Red).onClick(() => { AppStorage.setOrCreate('isLogin', true) ZRouter.popWithResult(true) }) } } `

已修复 1.0.4
